In [64]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(precision = 3, linewidth = 220)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convert complex modes to real modes

In [65]:
help(vt.real_modes)

Help on function real_modes in module vibrationtesting.system:

real_modes(Psi, autorotate=True)
    Real modes from complex modes.
    
    Assuming a transformation
    
    .. math:: Psi_{real} = Psi_{complex} T
    
    exists, where :math:`T` is a complex transformation matrix, find
    :math:`Psi_{real}` using linear algebra.
    
    Parameters
    ----------
    Psi : complex float array
        Complex mode shapes (displacement)
    autorotate : Boolean, optional
        Attempt to rotate to near-real first
    
    Returns
    -------
    Psi : float array
        Real modes
    
    Examples
    --------
    >>> import vibrationtesting as vt
    >>> M = np.array([[4, 0, 0],
    ...               [0, 4, 0],
    ...               [0, 0, 4]])
    >>> Cso = np.array([[.1,0,0],
    ...                 [0,0,0],
    ...                 [0,0,0]])
    >>> K = np.array([[8, -4, 0],
    ...               [-4, 8, -4],
    ...               [0, -4, 4]])
    >>> Bt = np.array([[1],[0],[0]

In [66]:
import vibrationtesting as vt
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
Cso = np.array([[1,0,0],
                [0,0,0],
                [0,0,0]])
K = np.array([[8, -4, 0],
              [-4, 8, -4],
              [0, -4, 4]])
omega, _, real_modes = vt.sos_modal(M, K)
Bt = np.array([[1],[0],[0]])
Ca = np.array([[1,0,0]])
Cd = Cv = np.zeros_like(Ca)
A, B, C, D = vt.so2ss(M, Cso, K, Bt, Cd, Cv, Ca)
Am, Bm, Cm, Dm, eigenvalues, modes = vt.ss_modal(A, B, C, D)
Psi = vt.real_modes(modes[:,0::2])

In [67]:
Psi/Psi[2,2]

array([[ 1.802,  2.786,  1.712],
       [ 3.284,  1.42 , -2.309],
       [ 4.01 , -2.311,  1.   ],
       [ 0.331,  1.255, -1.537],
       [-0.255, -1.998, -0.231],
       [-0.367,  0.537,  0.609]])

In [68]:
real_modes/real_modes[0,0]

array([[ 1.   , -2.247,  1.802],
       [ 1.802, -1.   , -2.247],
       [ 2.247,  1.802,  1.   ]])

In [69]:
modes

array([[ 0.299-0.021j,  0.299+0.021j, -0.025-0.463j, -0.025+0.463j, -0.06 +0.278j, -0.06 -0.278j],
       [ 0.54 -0.008j,  0.54 +0.008j,  0.054-0.203j,  0.054+0.203j, -0.009-0.36 j, -0.009+0.36 j],
       [ 0.673+0.   j,  0.673-0.   j,  0.015+0.363j,  0.015-0.363j,  0.015+0.161j,  0.015-0.161j],
       [ 0.005+0.133j,  0.005-0.133j,  0.579+0.   j,  0.579-0.   j, -0.497-0.119j, -0.497+0.119j],
       [-0.004+0.241j, -0.004-0.241j,  0.249+0.081j,  0.249-0.081j,  0.646+0.   j,  0.646-0.   j],
       [-0.009+0.3  j, -0.009-0.3  j, -0.453-0.006j, -0.453+0.006j, -0.29 +0.02 j, -0.29 -0.02 j]])