In [4]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
import matplotlib.pyplot as plt
import numpy as np
import array_to_latex as a2t
np.set_printoptions(precision = 3, linewidth = 220, suppress = True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convert complex modes to real modes

In [49]:
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
Cso = np.array([[1,0,0],
                [0,0,0],
                [0,0,0]])
K = np.array([[8, -4, 0],
              [-4, 8, -4],
              [0, -4, 4]])
omega, _, Psi_true = vt.sos_modal(M, K)
Bt = np.array([[1],[0],[0]])
Ca = np.array([[1,0,0]])
Cd = Cv = np.zeros_like(Ca)
A, B, C, D = vt.so2ss(M, Cso, K, Bt, Cd, Cv, Ca)
Am, Bm, Cm, Dm, eigenvalues, modes = vt.ss_modal(A, B, C, D)
complex_modes = modes[:3,0::2]
complex_modes = complex_modes@np.linalg.inv(np.diag(np.diag(complex_modes)))
Psi_est = vt.real_modes(complex_modes)


In [50]:
Psi_true/Psi_true[0,0]

array([[ 1.   , -2.247,  1.802],
       [ 1.802, -1.   , -2.247],
       [ 2.247,  1.802,  1.   ]])

In [51]:
np.real(complex_modes)

array([[ 1.   ,  2.099,  1.678],
       [ 1.798,  1.   , -2.218],
       [ 2.241, -1.651,  1.   ]])

In [52]:
np.abs(complex_modes)*np.real(np.sign(complex_modes))

array([[ 1.   ,  2.208,  1.759],
       [ 1.801,  1.   , -2.223],
       [ 2.246, -1.729,  1.   ]])

In [55]:
Psi_est

array([[ 1.   ,  2.208,  1.759],
       [ 1.803,  0.975, -2.116],
       [ 2.229, -1.761,  0.903]])

In [54]:
Psi_est@np.linalg.inv(np.diag(np.diag(Psi_est)))

array([[ 1.   ,  2.265,  1.948],
       [ 1.803,  1.   , -2.343],
       [ 2.229, -1.806,  1.   ]])

In [56]:
Psi_true.T@Psi_true


array([[ 0.25,  0.  , -0.  ],
       [ 0.  ,  0.25,  0.  ],
       [-0.  ,  0.  ,  0.25]])

In [ ]:
vt.ma