In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
import matplotlib.pyplot as plt
import numpy as np
import array_to_latex as a2t
np.set_printoptions(precision = 9, linewidth = 220, suppress = True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convert complex modes to real modes

In [4]:
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
Cso = np.array([[1,0,0],
                [0,0,0],
                [0,0,0]])
K = np.array([[8, -4, 0],
              [-4, 8, -4],
              [0, -4, 4]])
omega, _, Psi_true = vt.sos_modal(M, K)
Bt = np.array([[1],[0],[0]])
Ca = np.array([[1,0,0]])
Cd = Cv = np.zeros_like(Ca)
A, B, C, D = vt.so2ss(M, Cso, K, Bt, Cd, Cv, Ca)
Am, Bm, Cm, Dm, eigenvalues, modes = vt.ss_modal(A, B, C, D)
complex_modes = modes[:3,0::2]
complex_modes = complex_modes@np.linalg.inv(np.diag(np.diag(complex_modes)))
Psi_corrected = vt.real_modes(complex_modes)


In [5]:
Psi_true

array([[-0.163992639,  0.368488115, -0.295504524],
       [-0.295504524,  0.163992639,  0.368488115],
       [-0.368488115, -0.295504524, -0.163992639]])

In [6]:
complex_modes

array([[ 1.         +0.j         ,  2.099234839-0.684531423j,  1.678352494+0.52790572j ],
       [ 1.798247408+0.099411477j,  1.         -0.j         , -2.218125195-0.153628421j],
       [ 2.240934713+0.157537198j, -1.651470818+0.512991869j,  1.         -0.j         ]])

In [7]:
a2t.to_ltx(complex_modes, frmt = '{:3.5f}', imstring='j')

\begin{bmatrix}
  1.00000+0.00000j &  2.09923-0.68453j &  1.67835+0.52791j\\
  1.79825+0.09941j &  1.00000-0.00000j & -2.21813-0.15363j\\
  2.24093+0.15754j & -1.65147+0.51299j &  1.00000-0.00000j
\end{bmatrix}


In [8]:
Psi_real = np.real(complex_modes)
Psi_real

array([[ 1.         ,  2.099234839,  1.678352494],
       [ 1.798247408,  1.         , -2.218125195],
       [ 2.240934713, -1.651470818,  1.         ]])

In [9]:
a2t.to_ltx(Psi_true, frmt = '{:3.5f}')

\begin{bmatrix}
 -0.1639 &  0.3684 & -0.2955\\
 -0.2955 &  0.1639 &  0.3684\\
 -0.3684 & -0.2955 & -0.1639
\end{bmatrix}


In [10]:
?a2t.to_clp

In [11]:
Psi_abs = np.abs(complex_modes)*np.real(np.sign(complex_modes))
Psi_abs

array([[ 1.         ,  2.208024044,  1.759417956],
       [ 1.800993165,  1.         , -2.223439019],
       [ 2.246465302, -1.729310996,  1.         ]])

In [12]:
Psi_corrected

array([[ 1.         ,  2.208024044,  1.759417956],
       [ 1.80253425 ,  0.974920375, -2.116079409],
       [ 2.229245067, -1.760956913,  0.902996771]])

In [13]:
vt.mac(Psi_true,Psi_real)

array([[0.999999338, 0.000479191, 0.000063106],
       [0.000000603, 0.999343589, 0.000762406],
       [0.000000059, 0.00017722 , 0.999174488]])

In [14]:
a2t.to_ltx(vt.mac(Psi_true,Psi_real), frmt = '{:3.5f}')

\begin{bmatrix}
  1.0000 &  0.0004 &  0.0000\\
  0.0000 &  0.9993 &  0.0007\\
  0.0000 &  0.0001 &  0.9991
\end{bmatrix}


In [15]:
vt.mac(Psi_true,Psi_abs)

array([[0.99999997 , 0.000187273, 0.         ],
       [0.         , 0.999812655, 0.000061695],
       [0.00000003 , 0.000000072, 0.999938305]])

In [16]:
a2t.to_ltx(vt.mac(Psi_true,Psi_abs), frmt = '{:3.5f}')

\begin{bmatrix}
  1.0000 &  0.0001 &  0.0000\\
  0.0000 &  0.9998 &  0.0000\\
  0.0000 &  0.0000 &  0.9999
\end{bmatrix}


In [17]:
vt.mac(Psi_true,Psi_corrected)

array([[0.999983388, 0.000000759, 0.000007767],
       [0.000012366, 0.999990366, 0.000566347],
       [0.000004246, 0.000008875, 0.999425887]])

In [18]:
a2t.to_ltx(vt.mac(Psi_true,Psi_corrected), frmt = '{:3.5f}')

\begin{bmatrix}
  0.9999 &  0.0000 &  0.0000\\
  0.0000 &  0.9999 &  0.0005\\
  0.0000 &  0.0000 &  0.9994
\end{bmatrix}


In [19]:
Psi_real = vt.mass_normalize(Psi_real, M)

In [20]:
Psi_real.T@M@Psi_real

array([[ 1.         ,  0.022663407, -0.007723197],
       [ 0.022663407,  1.         , -0.041083449],
       [-0.007723197, -0.041083449,  1.         ]])

In [21]:
a2t.to_ltx(Psi_real.T@M@Psi_real)

\begin{bmatrix}
  1.0 &  0.0 & -0.0\\
  0.0 &  1.0 & -0.0\\
 -0.0 & -0.0 &  1.0
\end{bmatrix}


In [22]:
a2t.to_ltx(K)

\begin{bmatrix}
  8.0 & -4.0 &  0.0\\
 -4.0 &  8.0 & -4.0\\
  0.0 & -4.0 &  4.0
\end{bmatrix}
