In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import vibrationtesting as vt
import matplotlib.pyplot as plt
import numpy as np
import array_to_latex as a2t
np.set_printoptions(precision = 3, linewidth = 220, suppress = True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convert complex modes to real modes

In [4]:
M = np.array([[4, 0, 0],
              [0, 4, 0],
              [0, 0, 4]])
Cso = np.array([[1,0,0],
                [0,0,0],
                [0,0,0]])
K = np.array([[8, -4, 0],
              [-4, 8, -4],
              [0, -4, 4]])
omega, _, Psi_true = vt.sos_modal(M, K)
Bt = np.array([[1],[0],[0]])
Ca = np.array([[1,0,0]])
Cd = Cv = np.zeros_like(Ca)
A, B, C, D = vt.so2ss(M, Cso, K, Bt, Cd, Cv, Ca)
Am, Bm, Cm, Dm, eigenvalues, modes = vt.ss_modal(A, B, C, D)
complex_modes = modes[:3,0::2]
complex_modes = complex_modes@np.linalg.inv(np.diag(np.diag(complex_modes)))
Psi_est = vt.real_modes(complex_modes)


In [5]:
Psi_true/Psi_true[0,0]

array([[ 1.   , -2.247,  1.802],
       [ 1.802, -1.   , -2.247],
       [ 2.247,  1.802,  1.   ]])

In [6]:
np.real(complex_modes)

array([[ 1.   ,  2.099,  1.678],
       [ 1.798,  1.   , -2.218],
       [ 2.241, -1.651,  1.   ]])

In [7]:
np.abs(complex_modes)*np.real(np.sign(complex_modes))

array([[ 1.   ,  2.208,  1.759],
       [ 1.801,  1.   , -2.223],
       [ 2.246, -1.729,  1.   ]])

In [ ]:
Psi_est

In [8]:
Psi_est@np.linalg.inv(np.diag(np.diag(Psi_est)))

array([[ 1.   ,  2.265,  1.948],
       [ 1.803,  1.   , -2.343],
       [ 2.229, -1.806,  1.   ]])

In [9]:
Psi_true.T@Psi_true


array([[ 0.25,  0.  , -0.  ],
       [ 0.  ,  0.25,  0.  ],
       [-0.  ,  0.  ,  0.25]])

In [10]:
np.arange(3)

array([0, 1, 2])

In [11]:
Psi_true.shape[0]

3

In [12]:
Psi_true.shape == Psi_true.shape

True

In [13]:
Psi_true.shape

(3, 3)

In [14]:
help(vt.mac)

Help on function mac in module vibrationtesting.identification:

mac(Psi_1, Psi_2)
    Modal Assurance Criterion.
    
    Parameters
    ----------
    Psi_1, Psi_2 : float arrays
        Mode shape matrices to be compared.
    
    Returns
    -------
    mac : float array
    
    Examples
    --------

