In [99]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
sp.set_printoptions(precision=3)

import control as ctrl
import matplotlib.pyplot as plt
import scipy as sp
import scipy.linalg as la
import vibrationtesting as vt
import numpy.linalg as lanp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
help(vt.so2ss)

Help on function so2ss in module vibrationtesting.signal:

so2ss(M, C, K, Bt, Cd, Cv, Ca)
    returns A, B, C, D
    Given second order linear matrix equation of the form 
    :math:`M\ddot{x} + C \dot{x} + K x= Bt u`
    and
    :math:`y = Cd x + + Cv \dot{x} + Ca\ddot{x}`
    returns the state space form equations
    :math:`\dot{z} = A z + B u`
    :math:`y = C z + D u`



In [59]:
M = np.array([[1,0],[0,1]])
C = np.array([[0.4, -.1],[-.1,.2]])
K = np.array([[2,-1],[-1,2]])
Cd = sp.eye(2)
Cv = Cd*0
Ca = Cv
Bt = np.array([[1],[0]])

In [62]:
A, B, Css, D = vt.so2ss(M, C, K, Bt, Cd, Cv, Ca)

In [63]:
print('A = \n{},\n B = \n{},\n C = \n{},\n D = \n{}'.format(A, B, Css, D))

A = 
[[ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]
 [-2.   1.  -0.4  0.1]
 [ 1.  -2.   0.1 -0.2]],
 B = 
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]],
 C = 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]],
 D = 
[[ 0.]
 [ 0.]]


In [64]:
e, vec = la.eig(A)

In [65]:
vt.damp(A)

............... Eigenvalue ...........     Damping     Frequency
--------[re]---------[im]--------[abs]----------------------[Hz]
      -0.200        +1.716      1.728       0.116         0.275
      -0.200        -1.716      1.728       0.116         0.275
      -0.100        +0.998      1.003       0.100         0.160
      -0.100        -0.998      1.003       0.100         0.160


In [66]:
print(vec[:,0:1])

[[-0.041-0.354j]
 [ 0.101+0.338j]
 [ 0.615+0.j   ]
 [-0.600+0.106j]]


In [67]:
sp.set_printoptions(precision=3)
print('{}'.format(vec))

[[-0.041-0.354j -0.041+0.354j -0.100-0.489j -0.100+0.489j]
 [ 0.101+0.338j  0.101-0.338j -0.050-0.497j -0.050+0.497j]
 [ 0.615+0.j     0.615-0.j     0.498-0.05j   0.498+0.05j ]
 [-0.600+0.106j -0.600-0.106j  0.501+0.j     0.501-0.j   ]]


In [88]:
Ca = np.array([[1, 0]])
Cd = Ca*0
Cv = Cd
Bt = np.array([[1],[0]])
A, B, Css, D = vt.so2ss(M, C, K, Bt, Cd, Cv, Ca)

In [89]:
Ad, Bd, _, _ = vt.c2d(A, B, C, D, .1)

In [90]:
Ad

array([[  9.902e-01,   4.885e-03,   9.770e-02,   6.523e-04],
       [  4.918e-03,   9.901e-01,   6.523e-04,   9.868e-02],
       [ -1.948e-01,   9.640e-02,   9.512e-01,   1.452e-02],
       [  9.737e-02,  -1.967e-01,   1.452e-02,   9.704e-01]])

In [91]:
Bd

array([[  4.926e-03],
       [  2.050e-05],
       [  9.770e-02],
       [  6.523e-04]])

In [92]:
Css

array([[-2. ,  1. , -0.4,  0.1]])

In [93]:
D

array([[ 1.]])

In [94]:
help(ctrl.ctrb)

Help on function ctrb in module control.statefbk:

ctrb(A, B)
    Controllabilty matrix
    
    Parameters
    ----------
    A, B: array_like or string
        Dynamics and input matrix of the system
    
    Returns
    -------
    C: matrix
        Controllability matrix
    
    Examples
    --------
    >>> C = ctrb(A, B)



In [95]:
CC = ctrl.ctrb(Ad, Bd)
CC

matrix([[  4.926e-03,   1.442e-02,   2.327e-02,   3.133e-02],
        [  2.050e-05,   1.726e-04,   5.513e-04,   1.225e-03],
        [  9.770e-02,   9.198e-02,   8.473e-02,   7.619e-02],
        [  6.523e-04,   2.528e-03,   5.160e-03,   8.395e-03]])

In [100]:
lanp.matrix_rank(CC)

4

In [101]:
OO = ctrl.obsv(Ad, Css)
OO

matrix([[-2.   ,  1.   , -0.4  ,  0.1  ],
        [-1.888,  0.922, -0.574,  0.189],
        [-1.735,  0.811, -0.727,  0.264],
        [-1.546,  0.673, -0.856,  0.325]])

In [102]:
lanp.matrix_rank(OO)

4